"""initial_migration

Revision ID: 64675e4a64da
Revises: 
Create Date: 2026-07-23 12:14:03.546898

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '64675e4a64da'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=64), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('html_report', sa.Text(), nullable=False),
    sa.Column('terraform_zip_bytes', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migration_runs')
    # ### end Alembic commands ###
